// Short aliases for the generated Supabase types (database.types.ts is regenerated by `npm run db:types`).
import type { Database, Enums, Tables } from "./database.types";

export type { Database, Tables };
export type AppRole = Enums<"app_role">;
export type AppLanguage = Enums<"app_language">;
export type Profile = Tables<"profiles">;
export type FirmSettings = Tables<"firm_settings">;
export type ProjectStatus = Enums<"project_status">;
export type Company = Tables<"companies">;
export type CompanyListRow = Tables<"company_list">;
export type Contact = Tables<"contacts">;
export type Project = Tables<"projects">;
export type ProjectListRow = Tables<"project_list">;
export type ProjectParticipant = Tables<"project_participants">;
export type Lv = Tables<"lvs">;
export type LvStatus = Enums<"lv_status">;
export type Catalog = Tables<"catalogs">;
