// Short aliases for the generated Supabase types (database.types.ts is regenerated by `npm run db:types`).
import type { Database, Enums, Tables } from "./database.types";

export type { Database };
export type AppRole = Enums<"app_role">;
export type AppLanguage = Enums<"app_language">;
export type Profile = Tables<"profiles">;
export type FirmSettings = Tables<"firm_settings">;
