import type { AppLanguage } from "@/lib/supabase/database.types";

// Printed documents use the document's language, which can differ from the UI language.
const labels = {
  de: {
    page: (p: number, n: number) => `Seite ${p} von ${n}`,
    offerNo: "Offert Nr.",
    date: "Datum",
    project: "Projekt:",
    uid: "UID:",
    bank: "Bank:",
    iban: "IBAN:",
    bic: "BIC:",
    offer: "Offerte Nr.",
    pos: "Pos.",
    description: "Bezeichnung / Beschreibung",
    quantity: "Menge",
    price: "Preis",
    total: "Positionspreis",
    subtotal: "Zwischensumme",
    vat: "Mehrwertsteuer",
    grandTotal: "Rechnungsbetrag",
    inclVat: "inkl. MwSt.",
    validUntil: "Gültigkeit der Offerte bis zum:",
    regards: "Freundliche Grüsse",
    managingDirector: "Geschäftsführer",
  },
  fr: {
    page: (p: number, n: number) => `Page ${p} sur ${n}`,
    offerNo: "Offre n°",
    date: "Date",
    project: "Projet :",
    uid: "IDE :",
    bank: "Banque :",
    iban: "IBAN :",
    bic: "BIC :",
    offer: "Offre n°",
    pos: "Pos.",
    description: "Désignation / Description",
    quantity: "Quantité",
    price: "Prix",
    total: "Prix de position",
    subtotal: "Sous-total",
    vat: "TVA",
    grandTotal: "Montant total",
    inclVat: "TVA incl.",
    validUntil: "Validité de l'offre jusqu'au :",
    regards: "Meilleures salutations",
    managingDirector: "Directeur",
  },
  it: {
    page: (p: number, n: number) => `Pagina ${p} di ${n}`,
    offerNo: "Offerta n.",
    date: "Data",
    project: "Progetto:",
    uid: "IDI:",
    bank: "Banca:",
    iban: "IBAN:",
    bic: "BIC:",
    offer: "Offerta n.",
    pos: "Pos.",
    description: "Designazione / Descrizione",
    quantity: "Quantità",
    price: "Prezzo",
    total: "Prezzo posizione",
    subtotal: "Subtotale",
    vat: "IVA",
    grandTotal: "Importo totale",
    inclVat: "IVA incl.",
    validUntil: "Validità dell'offerta fino al:",
    regards: "Cordiali saluti",
    managingDirector: "Amministratore",
  },
} satisfies Record<AppLanguage, Record<string, unknown>>;

export const pdfLabels = (language: AppLanguage) => labels[language];
