import type { AppLanguage } from "@/lib/supabase/types";

// Printed documents use the document's language, which can differ from the UI language.
const labels = {
  de: {
    lv: "Leistungsverzeichnis",
    lvNo: "LV Nr.",
    submissionDeadline: "Eingabetermin",
    unit: "Einheit",
    unitPrice: "EP",
    amount: "Betrag",
    lumpSum: "psch",
    optional: "Eventualposition",
    totalOf: "Total",
    summary: "Zusammenstellung",
    totalExclVat: "Total exkl. MwSt.",
    totalInclVat: "Total inkl. MwSt.",
    discount: "Rabatt",
    skonto: "Skonto",
    deductions: "Abzüge",
    net: "Netto",
    estimate: "Kostenschätzung",
    bidder: "Unternehmer",
    placeDate: "Ort / Datum",
    signature: "Stempel / Unterschrift",
    optionalNote: "Eventualpositionen sind im Total nicht enthalten.",
    page: (p: number, n: number) => `Seite ${p} von ${n}`,
    offerNo: "Offert Nr.",
    date: "Datum",
    project: "Projekt:",
    uid: "UID:",
    bank: "Bank:",
    iban: "IBAN:",
    bic: "BIC:",
    offer: "Offerte Nr.",
    pos: "Pos.",
    description: "Bezeichnung / Beschreibung",
    quantity: "Menge",
    price: "Preis",
    total: "Positionspreis",
    subtotal: "Zwischensumme",
    vat: "Mehrwertsteuer",
    grandTotal: "Rechnungsbetrag",
    inclVat: "inkl. MwSt.",
    validUntil: "Gültigkeit der Offerte bis zum:",
    regards: "Freundliche Grüsse",
    managingDirector: "Geschäftsführer",
  },
  fr: {
    lv: "Descriptif",
    lvNo: "Descriptif n°",
    submissionDeadline: "Délai de remise",
    unit: "Unité",
    unitPrice: "PU",
    amount: "Montant",
    lumpSum: "forfait",
    optional: "Position éventuelle",
    totalOf: "Total",
    summary: "Récapitulation",
    totalExclVat: "Total hors TVA",
    totalInclVat: "Total TVA incl.",
    discount: "Rabais",
    skonto: "Escompte",
    deductions: "Déductions",
    net: "Net",
    estimate: "Estimation des coûts",
    bidder: "Entrepreneur",
    placeDate: "Lieu / date",
    signature: "Timbre / signature",
    optionalNote: "Les positions éventuelles ne sont pas comprises dans le total.",
    page: (p: number, n: number) => `Page ${p} sur ${n}`,
    offerNo: "Offre n°",
    date: "Date",
    project: "Projet :",
    uid: "IDE :",
    bank: "Banque :",
    iban: "IBAN :",
    bic: "BIC :",
    offer: "Offre n°",
    pos: "Pos.",
    description: "Désignation / Description",
    quantity: "Quantité",
    price: "Prix",
    total: "Prix de position",
    subtotal: "Sous-total",
    vat: "TVA",
    grandTotal: "Montant total",
    inclVat: "TVA incl.",
    validUntil: "Validité de l'offre jusqu'au :",
    regards: "Meilleures salutations",
    managingDirector: "Directeur",
  },
  it: {
    lv: "Capitolato",
    lvNo: "Capitolato n.",
    submissionDeadline: "Termine di consegna",
    unit: "Unità",
    unitPrice: "PU",
    amount: "Importo",
    lumpSum: "a corpo",
    optional: "Posizione eventuale",
    totalOf: "Totale",
    summary: "Riassunto",
    totalExclVat: "Totale IVA esclusa",
    totalInclVat: "Totale IVA inclusa",
    discount: "Sconto",
    skonto: "Sconto cassa",
    deductions: "Deduzioni",
    net: "Netto",
    estimate: "Stima dei costi",
    bidder: "Impresa",
    placeDate: "Luogo / data",
    signature: "Timbro / firma",
    optionalNote: "Le posizioni eventuali non sono comprese nel totale.",
    page: (p: number, n: number) => `Pagina ${p} di ${n}`,
    offerNo: "Offerta n.",
    date: "Data",
    project: "Progetto:",
    uid: "IDI:",
    bank: "Banca:",
    iban: "IBAN:",
    bic: "BIC:",
    offer: "Offerta n.",
    pos: "Pos.",
    description: "Designazione / Descrizione",
    quantity: "Quantità",
    price: "Prezzo",
    total: "Prezzo posizione",
    subtotal: "Subtotale",
    vat: "IVA",
    grandTotal: "Importo totale",
    inclVat: "IVA incl.",
    validUntil: "Validità dell'offerta fino al:",
    regards: "Cordiali saluti",
    managingDirector: "Amministratore",
  },
} satisfies Record<AppLanguage, Record<string, unknown>>;

export const pdfLabels = (language: AppLanguage) => labels[language];
