// GENERATED by scripts/gen-heating-material-data.mjs from the Nussbaum and Meier Tobler IGH catalogues – do not edit.
// Articles of the Materialauszug of 242 Wärmeerzeugung; thread sizes in inches, pipe sizes as Optipress outer diameter.

export type Article = { number: string; text: string };

export const thermPipes: (Article & { d: number })[] = [
  {
    "number": "55080.22",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 15",
    "d": 15
  },
  {
    "number": "55080.23",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 18",
    "d": 18
  },
  {
    "number": "55080.24",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 22",
    "d": 22
  },
  {
    "number": "55080.25",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 28",
    "d": 28
  },
  {
    "number": "55080.26",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 35",
    "d": 35
  },
  {
    "number": "55080.27",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 42",
    "d": 42
  },
  {
    "number": "55080.28",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 54",
    "d": 54
  },
  {
    "number": "55080.29",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 76.1",
    "d": 76.1
  },
  {
    "number": "55080.30",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 88.9",
    "d": 88.9
  },
  {
    "number": "55080.31",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 108",
    "d": 108
  },
  {
    "number": "55080.32",
    "text": "Optipress-Therm-Rohr, Stange à 6 m, 64",
    "d": 64
  }
];

export const thermBends90: (Article & { d: number })[] = [
  {
    "number": "55000.22",
    "text": "Optipress-Therm-Bogen 90°, 15",
    "d": 15
  },
  {
    "number": "55000.23",
    "text": "Optipress-Therm-Bogen 90°, 18",
    "d": 18
  },
  {
    "number": "55000.24",
    "text": "Optipress-Therm-Bogen 90°, 22",
    "d": 22
  },
  {
    "number": "55000.25",
    "text": "Optipress-Therm-Bogen 90°, 28",
    "d": 28
  },
  {
    "number": "55000.26",
    "text": "Optipress-Therm-Bogen 90°, 35",
    "d": 35
  },
  {
    "number": "55000.27",
    "text": "Optipress-Therm-Bogen 90°, 42",
    "d": 42
  },
  {
    "number": "55000.28",
    "text": "Optipress-Therm-Bogen 90°, 54",
    "d": 54
  },
  {
    "number": "55000.70",
    "text": "Optipress-Therm-Bogen 90°, 64",
    "d": 64
  },
  {
    "number": "55000.71",
    "text": "Optipress-Therm-Bogen 90°, 76.1",
    "d": 76.1
  },
  {
    "number": "55000.72",
    "text": "Optipress-Therm-Bogen 90°, 88.9",
    "d": 88.9
  },
  {
    "number": "55000.73",
    "text": "Optipress-Therm-Bogen 90°, 108",
    "d": 108
  }
];

export const thermBends45: (Article & { d: number })[] = [
  {
    "number": "55003.22",
    "text": "Optipress-Therm-Bogen 45°, 15",
    "d": 15
  },
  {
    "number": "55003.23",
    "text": "Optipress-Therm-Bogen 45°, 18",
    "d": 18
  },
  {
    "number": "55003.24",
    "text": "Optipress-Therm-Bogen 45°, 22",
    "d": 22
  },
  {
    "number": "55003.25",
    "text": "Optipress-Therm-Bogen 45°, 28",
    "d": 28
  },
  {
    "number": "55003.26",
    "text": "Optipress-Therm-Bogen 45°, 35",
    "d": 35
  },
  {
    "number": "55003.27",
    "text": "Optipress-Therm-Bogen 45°, 42",
    "d": 42
  },
  {
    "number": "55003.28",
    "text": "Optipress-Therm-Bogen 45°, 54",
    "d": 54
  },
  {
    "number": "55003.70",
    "text": "Optipress-Therm-Bogen 45°, 64",
    "d": 64
  },
  {
    "number": "55003.71",
    "text": "Optipress-Therm-Bogen 45°, 76.1",
    "d": 76.1
  },
  {
    "number": "55003.72",
    "text": "Optipress-Therm-Bogen 45°, 88.9",
    "d": 88.9
  },
  {
    "number": "55003.73",
    "text": "Optipress-Therm-Bogen 45°, 108",
    "d": 108
  }
];

export const thermTees: (Article & { d: number })[] = [
  {
    "number": "55010.22",
    "text": "Optipress-Therm-T-Stück, 15",
    "d": 15
  },
  {
    "number": "55010.23",
    "text": "Optipress-Therm-T-Stück, 18",
    "d": 18
  },
  {
    "number": "55010.24",
    "text": "Optipress-Therm-T-Stück, 22",
    "d": 22
  },
  {
    "number": "55010.25",
    "text": "Optipress-Therm-T-Stück, 28",
    "d": 28
  },
  {
    "number": "55010.26",
    "text": "Optipress-Therm-T-Stück, 35",
    "d": 35
  },
  {
    "number": "55010.27",
    "text": "Optipress-Therm-T-Stück, 42",
    "d": 42
  },
  {
    "number": "55010.28",
    "text": "Optipress-Therm-T-Stück, 54",
    "d": 54
  },
  {
    "number": "55010.60",
    "text": "Optipress-Therm-T-Stück, 64",
    "d": 64
  },
  {
    "number": "55010.61",
    "text": "Optipress-Therm-T-Stück, 76.1",
    "d": 76.1
  },
  {
    "number": "55010.62",
    "text": "Optipress-Therm-T-Stück, 88.9",
    "d": 88.9
  },
  {
    "number": "55010.63",
    "text": "Optipress-Therm-T-Stück, 108",
    "d": 108
  }
];

export const ballValves: (Article & { d: number })[] = [
  {
    "number": "82100.22",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 15",
    "d": 15
  },
  {
    "number": "82100.23",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 18",
    "d": 18
  },
  {
    "number": "82100.24",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 22",
    "d": 22
  },
  {
    "number": "82100.25",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 28",
    "d": 28
  },
  {
    "number": "82100.26",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 35",
    "d": 35
  },
  {
    "number": "82100.27",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 42",
    "d": 42
  },
  {
    "number": "82100.28",
    "text": "Optipress-Kugelhahn, mit Metallgriff, 54",
    "d": 54
  }
];

export const teesThreaded: (Article & { d: number; thread: number })[] = [
  {
    "number": "55013.22",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 15 x ½ x 15",
    "d": 15,
    "thread": 0.5
  },
  {
    "number": "55013.23",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 18 x ½ x 18",
    "d": 18,
    "thread": 0.5
  },
  {
    "number": "55013.25",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 22 x ½ x 22",
    "d": 22,
    "thread": 0.5
  },
  {
    "number": "55013.26",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 22 x ¾ x 22",
    "d": 22,
    "thread": 0.75
  },
  {
    "number": "55013.27",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 28 x ½ x 28",
    "d": 28,
    "thread": 0.5
  },
  {
    "number": "55013.28",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 28 x ¾ x 28",
    "d": 28,
    "thread": 0.75
  },
  {
    "number": "55013.29",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 35 x ½ x 35",
    "d": 35,
    "thread": 0.5
  },
  {
    "number": "55013.30",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 42 x ½ x 42",
    "d": 42,
    "thread": 0.5
  },
  {
    "number": "55013.31",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 54 x ½ x 54",
    "d": 54,
    "thread": 0.5
  },
  {
    "number": "55013.32",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 35 x ¾ x 35",
    "d": 35,
    "thread": 0.75
  },
  {
    "number": "55013.33",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 42 x ¾ x 42",
    "d": 42,
    "thread": 0.75
  },
  {
    "number": "55013.34",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 54 x ¾ x 54",
    "d": 54,
    "thread": 0.75
  },
  {
    "number": "55013.35",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 54 x 1 x 54",
    "d": 54,
    "thread": 1
  },
  {
    "number": "55013.36",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 28 x 1 x 28",
    "d": 28,
    "thread": 1
  },
  {
    "number": "55013.70",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 64 x ¾ x 64",
    "d": 64,
    "thread": 0.75
  },
  {
    "number": "55013.72",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 76.1 x ¾ x 76.1",
    "d": 76.1,
    "thread": 0.75
  },
  {
    "number": "55013.74",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 88.9 x ¾ x 88.9",
    "d": 88.9,
    "thread": 0.75
  },
  {
    "number": "55013.76",
    "text": "Optipress-Therm-T-Stück, mit Innengewinde, 108 x ¾ x 108",
    "d": 108,
    "thread": 0.75
  }
];

export const drainCocks: (Article & { thread: number })[] = [
  {
    "number": "55032.54",
    "text": "Füll- und Entleerkugelhahn, mit Aussengewinde, ½",
    "thread": 0.5
  }
];

export const checkValves: (Article & { d: number })[] = [
  {
    "number": "81163.22",
    "text": "Optipress-A-Rückflussverhinderer EA, 15",
    "d": 15
  },
  {
    "number": "81163.23",
    "text": "Optipress-A-Rückflussverhinderer EA, 18",
    "d": 18
  },
  {
    "number": "81163.24",
    "text": "Optipress-A-Rückflussverhinderer EA, 22",
    "d": 22
  },
  {
    "number": "81163.25",
    "text": "Optipress-A-Rückflussverhinderer EA, 28",
    "d": 28
  },
  {
    "number": "81163.26",
    "text": "Optipress-A-Rückflussverhinderer EA, 35",
    "d": 35
  },
  {
    "number": "81163.27",
    "text": "Optipress-A-Rückflussverhinderer EA, 42",
    "d": 42
  },
  {
    "number": "81163.28",
    "text": "Optipress-A-Rückflussverhinderer EA, 54",
    "d": 54
  }
];

export const potableSafetyValves: (Article & { thread: number })[] = [
  {
    "number": "13000.04",
    "text": "Sicherheitsventil, 6 bar fest eingestellt, ½",
    "thread": 0.5
  },
  {
    "number": "13000.05",
    "text": "Sicherheitsventil, 6 bar fest eingestellt, ¾",
    "thread": 0.75
  },
  {
    "number": "13000.06",
    "text": "Sicherheitsventil, 6 bar fest eingestellt, 1",
    "thread": 1
  }
];

export const afrisoValves: (Article & { thread: number; bar: number })[] = [
  {
    "number": "00310.200",
    "text": "Afriso Sicherheitsventil 1\", 3 bar",
    "thread": 1,
    "bar": 3
  },
  {
    "number": "00310.203",
    "text": "Afriso Sicherheitsventil 1\", 2,5 bar",
    "thread": 1,
    "bar": 2.5
  },
  {
    "number": "00310.204",
    "text": "Afriso Sicherheitsventil 1\", 3,5 bar",
    "thread": 1,
    "bar": 3.5
  },
  {
    "number": "00310.205",
    "text": "Afriso Sicherheitsventil 1\", 4 bar",
    "thread": 1,
    "bar": 4
  },
  {
    "number": "00310.212",
    "text": "Afriso Sicherheitsventil 1 1/4\", 3 bar",
    "thread": 1.25,
    "bar": 3
  },
  {
    "number": "00310.220",
    "text": "Afriso Sicherheitsventil 1/2\", 3 bar",
    "thread": 0.5,
    "bar": 3
  },
  {
    "number": "00310.222",
    "text": "Afriso Sicherheitsventil 1/2\", 2 bar",
    "thread": 0.5,
    "bar": 2
  },
  {
    "number": "00310.223",
    "text": "Afriso Sicherheitsventil 1/2\", 2,5 bar",
    "thread": 0.5,
    "bar": 2.5
  },
  {
    "number": "00310.224",
    "text": "Afriso Sicherheitsventil 1/2\", 3,5 bar",
    "thread": 0.5,
    "bar": 3.5
  },
  {
    "number": "00310.225",
    "text": "Afriso Sicherheitsventil 1/2\", 4 bar",
    "thread": 0.5,
    "bar": 4
  },
  {
    "number": "00310.226",
    "text": "Afriso Sicherheitsventil 1/2\", 1,5 bar",
    "thread": 0.5,
    "bar": 1.5
  },
  {
    "number": "00310.440",
    "text": "Afriso Sicherheitsventil 3/4\", 3 bar",
    "thread": 0.75,
    "bar": 3
  },
  {
    "number": "00310.442",
    "text": "Afriso Sicherheitsventil 3/4\", 2 bar",
    "thread": 0.75,
    "bar": 2
  },
  {
    "number": "00310.443",
    "text": "Afriso Sicherheitsventil 3/4\", 2,5 bar",
    "thread": 0.75,
    "bar": 2.5
  },
  {
    "number": "00310.444",
    "text": "Afriso Sicherheitsventil 3/4\", 3,5 bar",
    "thread": 0.75,
    "bar": 3.5
  },
  {
    "number": "00310.445",
    "text": "Afriso Sicherheitsventil 3/4\", 4 bar",
    "thread": 0.75,
    "bar": 4
  }
];

export const imiValves: (Article & { dn: number; bar: number })[] = [
  {
    "number": "00024.418",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 2.0 bar",
    "dn": 15,
    "bar": 2
  },
  {
    "number": "00024.419",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 2.5 bar",
    "dn": 15,
    "bar": 2.5
  },
  {
    "number": "00024.420",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 3.0 bar",
    "dn": 15,
    "bar": 3
  },
  {
    "number": "00024.421",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 3.5 bar",
    "dn": 15,
    "bar": 3.5
  },
  {
    "number": "00024.422",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 4.0 bar",
    "dn": 15,
    "bar": 4
  },
  {
    "number": "00024.423",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 4.5 bar",
    "dn": 15,
    "bar": 4.5
  },
  {
    "number": "00024.424",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 5.0 bar",
    "dn": 15,
    "bar": 5
  },
  {
    "number": "00024.425",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 5.5 bar",
    "dn": 15,
    "bar": 5.5
  },
  {
    "number": "00024.426",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 6.0 bar",
    "dn": 15,
    "bar": 6
  },
  {
    "number": "00024.427",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 7.0 bar",
    "dn": 15,
    "bar": 7
  },
  {
    "number": "00024.428",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 8.0 bar",
    "dn": 15,
    "bar": 8
  },
  {
    "number": "00024.429",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 9.0 bar",
    "dn": 15,
    "bar": 9
  },
  {
    "number": "00024.430",
    "text": "IMI DG/Hswiss Sicherheitsventil DN15 - 10.0 bar",
    "dn": 15,
    "bar": 10
  },
  {
    "number": "00024.431",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 2.0 bar",
    "dn": 20,
    "bar": 2
  },
  {
    "number": "00024.432",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 2.5 bar",
    "dn": 20,
    "bar": 2.5
  },
  {
    "number": "00024.433",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 3.0 bar",
    "dn": 20,
    "bar": 3
  },
  {
    "number": "00024.434",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 3.5 bar",
    "dn": 20,
    "bar": 3.5
  },
  {
    "number": "00024.435",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 4.0 bar",
    "dn": 20,
    "bar": 4
  },
  {
    "number": "00024.436",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 4.5 bar",
    "dn": 20,
    "bar": 4.5
  },
  {
    "number": "00024.437",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 5.0 bar",
    "dn": 20,
    "bar": 5
  },
  {
    "number": "00024.438",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 5.5 bar",
    "dn": 20,
    "bar": 5.5
  },
  {
    "number": "00024.439",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 6.0 bar",
    "dn": 20,
    "bar": 6
  },
  {
    "number": "00024.440",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 7.0 bar",
    "dn": 20,
    "bar": 7
  },
  {
    "number": "00024.441",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 8.0 bar",
    "dn": 20,
    "bar": 8
  },
  {
    "number": "00024.442",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 9.0 bar",
    "dn": 20,
    "bar": 9
  },
  {
    "number": "00024.443",
    "text": "IMI DG/Hswiss Sicherheitsventil DN20 - 10.0 bar",
    "dn": 20,
    "bar": 10
  },
  {
    "number": "00024.444",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 2.0 bar",
    "dn": 25,
    "bar": 2
  },
  {
    "number": "00024.445",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 2.5 bar",
    "dn": 25,
    "bar": 2.5
  },
  {
    "number": "00024.446",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 3.0 bar",
    "dn": 25,
    "bar": 3
  },
  {
    "number": "00024.447",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 3.5 bar",
    "dn": 25,
    "bar": 3.5
  },
  {
    "number": "00024.448",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 4.0 bar",
    "dn": 25,
    "bar": 4
  },
  {
    "number": "00024.449",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 4.5 bar",
    "dn": 25,
    "bar": 4.5
  },
  {
    "number": "00024.450",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 5.0 bar",
    "dn": 25,
    "bar": 5
  },
  {
    "number": "00024.451",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 5.5 bar",
    "dn": 25,
    "bar": 5.5
  },
  {
    "number": "00024.452",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 6.0 bar",
    "dn": 25,
    "bar": 6
  },
  {
    "number": "00024.453",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 7.0 bar",
    "dn": 25,
    "bar": 7
  },
  {
    "number": "00024.454",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 8.0 bar",
    "dn": 25,
    "bar": 8
  },
  {
    "number": "00024.455",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 9.0 bar",
    "dn": 25,
    "bar": 9
  },
  {
    "number": "00024.456",
    "text": "IMI DG/Hswiss Sicherheitsventil DN25 - 10.0 bar",
    "dn": 25,
    "bar": 10
  },
  {
    "number": "00024.457",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 2.0 bar",
    "dn": 32,
    "bar": 2
  },
  {
    "number": "00024.458",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 2.5 bar",
    "dn": 32,
    "bar": 2.5
  },
  {
    "number": "00024.459",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 3.0 bar",
    "dn": 32,
    "bar": 3
  },
  {
    "number": "00024.460",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 3.5 bar",
    "dn": 32,
    "bar": 3.5
  },
  {
    "number": "00024.461",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 4.0 bar",
    "dn": 32,
    "bar": 4
  },
  {
    "number": "00024.462",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 4.5 bar",
    "dn": 32,
    "bar": 4.5
  },
  {
    "number": "00024.463",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 5.0 bar",
    "dn": 32,
    "bar": 5
  },
  {
    "number": "00024.464",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 5.5 bar",
    "dn": 32,
    "bar": 5.5
  },
  {
    "number": "00024.465",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 6.0 bar",
    "dn": 32,
    "bar": 6
  },
  {
    "number": "00024.466",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 7.0 bar",
    "dn": 32,
    "bar": 7
  },
  {
    "number": "00024.467",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 8.0 bar",
    "dn": 32,
    "bar": 8
  },
  {
    "number": "00024.468",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 9.0 bar",
    "dn": 32,
    "bar": 9
  },
  {
    "number": "00024.469",
    "text": "IMI DG/Hswiss Sicherheitsventil DN32 - 10.0 bar",
    "dn": 32,
    "bar": 10
  },
  {
    "number": "00024.470",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 3.0 bar",
    "dn": 40,
    "bar": 3
  },
  {
    "number": "00024.471",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 3.5 bar",
    "dn": 40,
    "bar": 3.5
  },
  {
    "number": "00024.472",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 4.0 bar",
    "dn": 40,
    "bar": 4
  },
  {
    "number": "00024.473",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 4.5 bar",
    "dn": 40,
    "bar": 4.5
  },
  {
    "number": "00024.474",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 5.0 bar",
    "dn": 40,
    "bar": 5
  },
  {
    "number": "00024.475",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 5.5 bar",
    "dn": 40,
    "bar": 5.5
  },
  {
    "number": "00024.476",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 6.0 bar",
    "dn": 40,
    "bar": 6
  },
  {
    "number": "00024.477",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 7.0 bar",
    "dn": 40,
    "bar": 7
  },
  {
    "number": "00024.478",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 8.0 bar",
    "dn": 40,
    "bar": 8
  },
  {
    "number": "00024.479",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 9.0 bar",
    "dn": 40,
    "bar": 9
  },
  {
    "number": "00024.480",
    "text": "IMI DG/Hswiss Sicherheitsventil DN40 - 10.0 bar",
    "dn": 40,
    "bar": 10
  },
  {
    "number": "00024.481",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 3.0 bar",
    "dn": 50,
    "bar": 3
  },
  {
    "number": "00024.482",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 3.5 bar",
    "dn": 50,
    "bar": 3.5
  },
  {
    "number": "00024.483",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 4.0 bar",
    "dn": 50,
    "bar": 4
  },
  {
    "number": "00024.484",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 4.5 bar",
    "dn": 50,
    "bar": 4.5
  },
  {
    "number": "00024.485",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 5.0 bar",
    "dn": 50,
    "bar": 5
  },
  {
    "number": "00024.486",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 5.5 bar",
    "dn": 50,
    "bar": 5.5
  },
  {
    "number": "00024.487",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 6.0 bar",
    "dn": 50,
    "bar": 6
  },
  {
    "number": "00024.488",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 7.0 bar",
    "dn": 50,
    "bar": 7
  },
  {
    "number": "00024.489",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 8.0 bar",
    "dn": 50,
    "bar": 8
  },
  {
    "number": "00024.490",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 9.0 bar",
    "dn": 50,
    "bar": 9
  },
  {
    "number": "00024.491",
    "text": "IMI DG/Hswiss Sicherheitsventil DN50 - 10.0 bar",
    "dn": 50,
    "bar": 10
  }
];

export const drainValves: (Article & { thread: number })[] = [
  {
    "number": "00276.350",
    "text": "Meier Tobler ELV Entleerhahnen 3/8\"",
    "thread": 0.375
  },
  {
    "number": "00276.351",
    "text": "Meier Tobler ELV Entleerhahnen 1/2\"",
    "thread": 0.5
  }
];

export const vessels: (Article & { volume: number })[] = [
  {
    "number": "00862.092",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 8",
    "volume": 8
  },
  {
    "number": "00862.093",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 12",
    "volume": 12
  },
  {
    "number": "00862.094",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 18",
    "volume": 18
  },
  {
    "number": "00862.095",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 25",
    "volume": 25
  },
  {
    "number": "00862.096",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 35",
    "volume": 35
  },
  {
    "number": "00862.097",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 50",
    "volume": 50
  },
  {
    "number": "00862.098",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 80",
    "volume": 80
  },
  {
    "number": "00862.099",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 100",
    "volume": 100
  },
  {
    "number": "00862.100",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 140",
    "volume": 140
  },
  {
    "number": "00862.102",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 200",
    "volume": 200
  },
  {
    "number": "00862.103",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 300",
    "volume": 300
  },
  {
    "number": "00862.104",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 400",
    "volume": 400
  },
  {
    "number": "00862.105",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 500",
    "volume": 500
  },
  {
    "number": "00862.106",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 600",
    "volume": 600
  },
  {
    "number": "00862.107",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 800",
    "volume": 800
  },
  {
    "number": "00862.118",
    "text": "Reflex N Membran-Druckausdehnungsgefäss grau 250",
    "volume": 250
  }
];

export const capValves: (Article & { thread: number })[] = [
  {
    "number": "00862.160",
    "text": "Reflex SU Kappenventil R ¾\" x R ¾\"",
    "thread": 0.75
  },
  {
    "number": "00860.141",
    "text": "Reflex SU Kappenventil R 1\" x R 1\"",
    "thread": 1
  }
];

export const vesselBrackets: (Article & { min: number; max: number })[] = [
  {
    "number": "00862.161",
    "text": "Reflex Wandhalterung mit Spannband und Konsole 8 - 25 l",
    "min": 8,
    "max": 25
  }
];

export const manometers: (Article & { range: number })[] = [
  {
    "number": "00433.931",
    "text": "Afriso Manometer 80 mm 0 - 1.0 bar",
    "range": 1
  },
  {
    "number": "00433.932",
    "text": "Afriso Manometer 80 mm 0 - 2.5 bar",
    "range": 2.5
  },
  {
    "number": "00433.933",
    "text": "Afriso Manometer 80 mm 0 - 4.0 bar",
    "range": 4
  },
  {
    "number": "00433.934",
    "text": "Afriso Manometer 80 mm 0 - 6.0 bar",
    "range": 6
  },
  {
    "number": "00433.935",
    "text": "Afriso Manometer 80 mm 0 - 10.0 bar",
    "range": 10
  },
  {
    "number": "00433.936",
    "text": "Afriso Manometer 80 mm 0 - 16.0 bar",
    "range": 16
  },
  {
    "number": "00433.937",
    "text": "Afriso Manometer 80 mm 0 - 25.0 bar",
    "range": 25
  }
];

export const pumps: (Article & { series: "PrimAX" | "ModulA"; medium: "heating" | "brine"; dn: number; head: number; length: number })[] = [
  {
    "number": "00072.340",
    "text": "Biral PrimAX Heizungsumwälzpumpe 15-3 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 15,
    "head": 3,
    "length": 130
  },
  {
    "number": "00072.341",
    "text": "Biral PrimAX Heizungsumwälzpumpe 15-4 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 15,
    "head": 4,
    "length": 130
  },
  {
    "number": "00072.342",
    "text": "Biral PrimAX Heizungsumwälzpumpe 15-5 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 15,
    "head": 5,
    "length": 130
  },
  {
    "number": "00072.343",
    "text": "Biral PrimAX Heizungsumwälzpumpe 15-6 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 15,
    "head": 6,
    "length": 130
  },
  {
    "number": "00072.344",
    "text": "Biral PrimAX Heizungsumwälzpumpe 15-8 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 15,
    "head": 8,
    "length": 130
  },
  {
    "number": "00072.345",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-3 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 3,
    "length": 130
  },
  {
    "number": "00072.346",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-4 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 4,
    "length": 130
  },
  {
    "number": "00072.347",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-5 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 5,
    "length": 130
  },
  {
    "number": "00072.348",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-6 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 6,
    "length": 130
  },
  {
    "number": "00072.349",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-8 130 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 8,
    "length": 130
  },
  {
    "number": "00072.350",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-3 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 3,
    "length": 180
  },
  {
    "number": "00072.351",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-4 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 4,
    "length": 180
  },
  {
    "number": "00072.352",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-5 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 5,
    "length": 180
  },
  {
    "number": "00072.353",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-6 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 6,
    "length": 180
  },
  {
    "number": "00072.354",
    "text": "Biral PrimAX Heizungsumwälzpumpe 25-8 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 25,
    "head": 8,
    "length": 180
  },
  {
    "number": "00072.355",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-3 170 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 3,
    "length": 170
  },
  {
    "number": "00072.356",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-4 170 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 4,
    "length": 170
  },
  {
    "number": "00072.357",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-5 170 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 5,
    "length": 170
  },
  {
    "number": "00072.358",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-6 170 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 6,
    "length": 170
  },
  {
    "number": "00072.359",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-8 170 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 8,
    "length": 170
  },
  {
    "number": "00072.360",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-3 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 3,
    "length": 180
  },
  {
    "number": "00072.361",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-4 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 4,
    "length": 180
  },
  {
    "number": "00072.362",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-5 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 5,
    "length": 180
  },
  {
    "number": "00072.363",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-6 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 6,
    "length": 180
  },
  {
    "number": "00072.364",
    "text": "Biral PrimAX Heizungsumwälzpumpe 32-8 180 RED T2",
    "series": "PrimAX",
    "medium": "heating",
    "dn": 32,
    "head": 8,
    "length": 180
  },
  {
    "number": "00071.041",
    "text": "Biral ModulA Heizungsumwälzpumpe 25-4 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 25,
    "head": 4,
    "length": 180
  },
  {
    "number": "00071.042",
    "text": "Biral ModulA Heizungsumwälzpumpe 25-6 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 25,
    "head": 6,
    "length": 180
  },
  {
    "number": "00071.043",
    "text": "Biral ModulA Heizungsumwälzpumpe 25-8 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 25,
    "head": 8,
    "length": 180
  },
  {
    "number": "00071.044",
    "text": "Biral ModulA Heizungsumwälzpumpe 25-10 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 25,
    "head": 10,
    "length": 180
  },
  {
    "number": "00071.045",
    "text": "Biral ModulA Heizungsumwälzpumpe 25-12 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 25,
    "head": 12,
    "length": 180
  },
  {
    "number": "00071.046",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-4 170 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 4,
    "length": 170
  },
  {
    "number": "00071.047",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-6 170 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 6,
    "length": 170
  },
  {
    "number": "00071.048",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-8 170 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 8,
    "length": 170
  },
  {
    "number": "00071.049",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-10 170 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 10,
    "length": 170
  },
  {
    "number": "00071.050",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-12 170 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 12,
    "length": 170
  },
  {
    "number": "00071.051",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-4 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 4,
    "length": 180
  },
  {
    "number": "00071.052",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-6 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 6,
    "length": 180
  },
  {
    "number": "00071.053",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-8 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 8,
    "length": 180
  },
  {
    "number": "00071.054",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-10 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 10,
    "length": 180
  },
  {
    "number": "00071.055",
    "text": "Biral ModulA Heizungsumwälzpumpe 32-12 180 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 12,
    "length": 180
  },
  {
    "number": "00071.056",
    "text": "Biral ModulA Heizungsumwälzpumpe 32F-6 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 6,
    "length": 220
  },
  {
    "number": "00071.057",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-4 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 4,
    "length": 220
  },
  {
    "number": "00071.058",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-6 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 6,
    "length": 220
  },
  {
    "number": "00071.059",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-11 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 11,
    "length": 220
  },
  {
    "number": "00071.060",
    "text": "Biral ModulA Heizungsumwälzpumpe 32F-12 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 32,
    "head": 12,
    "length": 220
  },
  {
    "number": "00071.061",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-8 220 RED T",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 8,
    "length": 220
  },
  {
    "number": "00071.062",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-10 220 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 10,
    "length": 220
  },
  {
    "number": "00071.063",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-12 250 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 12,
    "length": 250
  },
  {
    "number": "00071.064",
    "text": "Biral ModulA Heizungsumwälzpumpe 40-18 250 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 40,
    "head": 18,
    "length": 250
  },
  {
    "number": "00071.065",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-6 240 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 6,
    "length": 240
  },
  {
    "number": "00071.066",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-6 270 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 6,
    "length": 270
  },
  {
    "number": "00071.067",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-8 240 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 8,
    "length": 240
  },
  {
    "number": "00071.068",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-12 270 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 12,
    "length": 270
  },
  {
    "number": "00071.069",
    "text": "Biral ModulA Heizungsumwälzpumpe 50-18 270 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 50,
    "head": 18,
    "length": 270
  },
  {
    "number": "00071.070",
    "text": "Biral ModulA Heizungsumwälzpumpe 65-6 270 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 65,
    "head": 6,
    "length": 270
  },
  {
    "number": "00071.071",
    "text": "Biral ModulA Heizungsumwälzpumpe 65-8 270 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 65,
    "head": 8,
    "length": 270
  },
  {
    "number": "00071.072",
    "text": "Biral ModulA Heizungsumwälzpumpe 65-8 340 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 65,
    "head": 8,
    "length": 340
  },
  {
    "number": "00071.073",
    "text": "Biral ModulA Heizungsumwälzpumpe 65-12 340 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 65,
    "head": 12,
    "length": 340
  },
  {
    "number": "00071.074",
    "text": "Biral ModulA Heizungsumwälzpumpe 65-15 340 RED T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 65,
    "head": 15,
    "length": 340
  },
  {
    "number": "00071.075",
    "text": "Biral ModulA Heizungsumwälzpumpe 80-8 360 RED PN6 T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 80,
    "head": 8,
    "length": 360
  },
  {
    "number": "00071.077",
    "text": "Biral ModulA Heizungsumwälzpumpe 80-12 360 RED PN6 T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 80,
    "head": 12,
    "length": 360
  },
  {
    "number": "00071.079",
    "text": "Biral ModulA Heizungsumwälzpumpe 100-8 450 RED PN6 T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 100,
    "head": 8,
    "length": 450
  },
  {
    "number": "00071.081",
    "text": "Biral ModulA Heizungsumwälzpumpe 100-12 450 RED PN6 T2",
    "series": "ModulA",
    "medium": "heating",
    "dn": 100,
    "head": 12,
    "length": 450
  },
  {
    "number": "00071.439",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32F-12 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 12,
    "length": 220
  },
  {
    "number": "00071.440",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-8 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 8,
    "length": 220
  },
  {
    "number": "00071.441",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-10 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 10,
    "length": 220
  },
  {
    "number": "00071.442",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-12 250 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 12,
    "length": 250
  },
  {
    "number": "00071.443",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-18 250 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 18,
    "length": 250
  },
  {
    "number": "00071.444",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-6 240 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 6,
    "length": 240
  },
  {
    "number": "00071.445",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-6 270 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 6,
    "length": 270
  },
  {
    "number": "00071.446",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-8 240 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 8,
    "length": 240
  },
  {
    "number": "00071.447",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-12 270 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 12,
    "length": 270
  },
  {
    "number": "00071.448",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-18 270 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 18,
    "length": 270
  },
  {
    "number": "00071.449",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 65-6 270 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 65,
    "head": 6,
    "length": 270
  },
  {
    "number": "00071.450",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 65-8 270 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 65,
    "head": 8,
    "length": 270
  },
  {
    "number": "00071.451",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 65-8 340 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 65,
    "head": 8,
    "length": 340
  },
  {
    "number": "00071.452",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 65-12 340 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 65,
    "head": 12,
    "length": 340
  },
  {
    "number": "00071.453",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 65-15 340 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 65,
    "head": 15,
    "length": 340
  },
  {
    "number": "00071.454",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 80-8 360 GREEN PN6 T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 80,
    "head": 8,
    "length": 360
  },
  {
    "number": "00071.456",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 80-12 360 GREEN PN6 T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 80,
    "head": 12,
    "length": 360
  },
  {
    "number": "00071.458",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 100-8 450 GREEN PN6 T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 100,
    "head": 8,
    "length": 450
  },
  {
    "number": "00071.460",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 100-12 450 GREEN PN6 T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 100,
    "head": 12,
    "length": 450
  },
  {
    "number": "00071.600",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 25-4 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 25,
    "head": 4,
    "length": 180
  },
  {
    "number": "00071.601",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 25-6 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 25,
    "head": 6,
    "length": 180
  },
  {
    "number": "00071.602",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 25-8 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 25,
    "head": 8,
    "length": 180
  },
  {
    "number": "00071.603",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 25-10 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 25,
    "head": 10,
    "length": 180
  },
  {
    "number": "00071.604",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 25-12 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 25,
    "head": 12,
    "length": 180
  },
  {
    "number": "00071.605",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-4 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 4,
    "length": 180
  },
  {
    "number": "00071.606",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-6 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 6,
    "length": 180
  },
  {
    "number": "00071.607",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-8 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 8,
    "length": 180
  },
  {
    "number": "00071.608",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-10 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 10,
    "length": 180
  },
  {
    "number": "00071.609",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-12 180 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 12,
    "length": 180
  },
  {
    "number": "00071.610",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-4 170 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 4,
    "length": 170
  },
  {
    "number": "00071.611",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-6 170 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 6,
    "length": 170
  },
  {
    "number": "00071.612",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-8 170 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 8,
    "length": 170
  },
  {
    "number": "00071.613",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-10 170 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 10,
    "length": 170
  },
  {
    "number": "00071.614",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32-12 170 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 12,
    "length": 170
  },
  {
    "number": "00071.615",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 32F-6 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 32,
    "head": 6,
    "length": 220
  },
  {
    "number": "00071.616",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-4 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 4,
    "length": 220
  },
  {
    "number": "00071.617",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 40-6 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 40,
    "head": 6,
    "length": 220
  },
  {
    "number": "00071.618",
    "text": "Biral ModulA Kaltwasserumwälzpumpe 50-11 220 GREEN T2",
    "series": "ModulA",
    "medium": "brine",
    "dn": 50,
    "head": 11,
    "length": 220
  }
];

export const mixingValves: (Article & { dn: number; kvs: number })[] = [
  {
    "number": "00121.609",
    "text": "Siemens Dreiweg-Ventil VXG44.15-0.25",
    "dn": 15,
    "kvs": 0.25
  },
  {
    "number": "00121.610",
    "text": "Siemens Dreiweg-Ventil VXG44.15-0.4",
    "dn": 15,
    "kvs": 0.4
  },
  {
    "number": "00121.611",
    "text": "Siemens Dreiweg-Ventil VXG44.15-0.63",
    "dn": 15,
    "kvs": 0.63
  },
  {
    "number": "00121.612",
    "text": "Siemens Dreiweg-Ventil VXG44.15-1",
    "dn": 15,
    "kvs": 1
  },
  {
    "number": "00121.613",
    "text": "Siemens Dreiweg-Ventil VXG44.15-1.6",
    "dn": 15,
    "kvs": 1.6
  },
  {
    "number": "00121.614",
    "text": "Siemens Dreiweg-Ventil VXG44.15-2.5",
    "dn": 15,
    "kvs": 2.5
  },
  {
    "number": "00121.615",
    "text": "Siemens Dreiweg-Ventil VXG44.15-4",
    "dn": 15,
    "kvs": 4
  },
  {
    "number": "00121.620",
    "text": "Siemens Dreiweg-Ventil VXG44.20-6.3",
    "dn": 20,
    "kvs": 6.3
  },
  {
    "number": "00121.625",
    "text": "Siemens Dreiweg-Ventil VXG44.25-10",
    "dn": 25,
    "kvs": 10
  },
  {
    "number": "00121.632",
    "text": "Siemens Dreiweg-Ventil VXG44.32-16",
    "dn": 32,
    "kvs": 16
  },
  {
    "number": "00121.640",
    "text": "Siemens Dreiweg-Ventil VXG44.40-25",
    "dn": 40,
    "kvs": 25
  }
];

export const throughValves: (Article & { dn: number; kvs: number })[] = [
  {
    "number": "00121.601",
    "text": "Siemens Durchgangs-Ventil VVG44.15-0.25",
    "dn": 15,
    "kvs": 0.25
  },
  {
    "number": "00121.602",
    "text": "Siemens Durchgangs-Ventil VVG44.15-0.4",
    "dn": 15,
    "kvs": 0.4
  },
  {
    "number": "00121.603",
    "text": "Siemens Durchgangs-Ventil VVG44.15-0.63",
    "dn": 15,
    "kvs": 0.63
  },
  {
    "number": "00121.604",
    "text": "Siemens Durchgangs-Ventil VVG44.15-1",
    "dn": 15,
    "kvs": 1
  },
  {
    "number": "00121.605",
    "text": "Siemens Durchgangs-Ventil VVG44.15-1.6",
    "dn": 15,
    "kvs": 1.6
  },
  {
    "number": "00121.606",
    "text": "Siemens Durchgangs-Ventil VVG44.15-2.5",
    "dn": 15,
    "kvs": 2.5
  },
  {
    "number": "00121.607",
    "text": "Siemens Durchgangs-Ventil VVG44.15-4",
    "dn": 15,
    "kvs": 4
  },
  {
    "number": "00121.621",
    "text": "Siemens Durchgangs-Ventil VVG44.20-6.3",
    "dn": 20,
    "kvs": 6.3
  },
  {
    "number": "00121.626",
    "text": "Siemens Durchgangs-Ventil VVG44.25-10",
    "dn": 25,
    "kvs": 10
  },
  {
    "number": "00121.633",
    "text": "Siemens Durchgangs-Ventil VVG44.32-16",
    "dn": 32,
    "kvs": 16
  },
  {
    "number": "00121.641",
    "text": "Siemens Durchgangs-Ventil VVG44.40-25",
    "dn": 40,
    "kvs": 25
  }
];

export const diverterValves: (Article & { dn: number; kvs: number })[] = [
  {
    "number": "00120.250",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.50-37L",
    "dn": 50,
    "kvs": 37
  },
  {
    "number": "00120.251",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.40-25L",
    "dn": 40,
    "kvs": 25
  },
  {
    "number": "00120.252",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.32-13L",
    "dn": 32,
    "kvs": 13
  },
  {
    "number": "00120.253",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.25-9L",
    "dn": 25,
    "kvs": 9
  },
  {
    "number": "00120.254",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.15-5L",
    "dn": 15,
    "kvs": 5
  },
  {
    "number": "00120.255",
    "text": "Siemens 3-Weg Umschaltkugelhahn VBI60.20-9L",
    "dn": 20,
    "kvs": 9
  }
];

export const actuators: (Article & { type: "SAS61.03" | "GLB161.9E" })[] = [
  {
    "number": "00121.393",
    "text": "Siemens Stellantrieb SAS61.03",
    "type": "SAS61.03"
  },
  {
    "number": "00120.231",
    "text": "Siemens Stellantrieb GLB161.9E",
    "type": "GLB161.9E"
  }
];

export const balancingValves: (Article & { dn: number })[] = [
  {
    "number": "00435.171",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 10 IG",
    "dn": 10
  },
  {
    "number": "00435.172",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 15 IG",
    "dn": 15
  },
  {
    "number": "00435.173",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 20 IG",
    "dn": 20
  },
  {
    "number": "00435.174",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 25 IG",
    "dn": 25
  },
  {
    "number": "00435.175",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 32 IG",
    "dn": 32
  },
  {
    "number": "00435.176",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 40 IG",
    "dn": 40
  },
  {
    "number": "00435.177",
    "text": "IMI STAD Einregulierungsventil m. Entleeradapter DN 50 IG",
    "dn": 50
  }
];

export const heatMeters: (Article & { qp: number; thread: number })[] = [
  {
    "number": "51550.100",
    "text": "GWF UltraMaXX Vs Wärmezähler M-Bus qp1.5 1\"x130 mm, DM",
    "qp": 1.5,
    "thread": 1
  },
  {
    "number": "51550.102",
    "text": "GWF UltraMaXX Vs Wärmezähler M-Bus qp2.5 1\"x130 mm, DM",
    "qp": 2.5,
    "thread": 1
  },
  {
    "number": "51550.104",
    "text": "GWF UltraMaXX Vs Wärmezähler M-Bus qp1.5 3/4\"x110 mm, DM",
    "qp": 1.5,
    "thread": 0.75
  }
];

export const thermometers: (Article)[] = [
  {
    "number": "53020.151",
    "text": "Meier Tobler Thermometer mit Messingtauchhülse Ø 80 mm 0-120 100 mm"
  }
];

export const pePipes: (Article & { d: number; wall: number; roll: number })[] = [
  {
    "number": "92100.120",
    "text": "HakaGerodur GEROthen Druckrohr PE 20x2,0 mm PN16 50 m",
    "d": 20,
    "wall": 2,
    "roll": 50
  },
  {
    "number": "92100.121",
    "text": "HakaGerodur GEROthen Druckrohr PE 20x2,0 mm PN16 100 m",
    "d": 20,
    "wall": 2,
    "roll": 100
  },
  {
    "number": "92100.125",
    "text": "HakaGerodur GEROthen Druckrohr PE 25x2,3 mm PN16 50 m",
    "d": 25,
    "wall": 2.3,
    "roll": 50
  },
  {
    "number": "92100.126",
    "text": "HakaGerodur GEROthen Druckrohr PE 25x2,3 mm PN16 100 m",
    "d": 25,
    "wall": 2.3,
    "roll": 100
  },
  {
    "number": "92100.132",
    "text": "HakaGerodur GEROthen Druckrohr PE 32x2,9 mm PN16 50 m",
    "d": 32,
    "wall": 2.9,
    "roll": 50
  },
  {
    "number": "92100.133",
    "text": "HakaGerodur GEROthen Druckrohr PE 2x2,9 mm PN16 100 m",
    "d": 2,
    "wall": 2.9,
    "roll": 100
  },
  {
    "number": "92100.140",
    "text": "HakaGerodur GEROthen Druckrohr PE 40x3,7 mm PN16 50 m",
    "d": 40,
    "wall": 3.7,
    "roll": 50
  },
  {
    "number": "92100.141",
    "text": "HakaGerodur GEROthen Druckrohr PE 40x3,7 mm PN16 100 m",
    "d": 40,
    "wall": 3.7,
    "roll": 100
  },
  {
    "number": "92100.150",
    "text": "HakaGerodur GEROthen Druckrohr PE 50x4,6 mm PN16 50 m",
    "d": 50,
    "wall": 4.6,
    "roll": 50
  },
  {
    "number": "92100.151",
    "text": "HakaGerodur GEROthen Druckrohr PE 50x4,6 mm PN16 100 m",
    "d": 50,
    "wall": 4.6,
    "roll": 100
  },
  {
    "number": "92100.163",
    "text": "HakaGerodur GEROthen Druckrohr PE 63x5,8 mm PN16 50 m",
    "d": 63,
    "wall": 5.8,
    "roll": 50
  },
  {
    "number": "92100.164",
    "text": "HakaGerodur GEROthen Druckrohr PE 63x5,8 mm PN16 100 m",
    "d": 63,
    "wall": 5.8,
    "roll": 100
  },
  {
    "number": "92100.175",
    "text": "HakaGerodur GEROthen Druckrohr PE 75x6,8 mm PN16 50 m",
    "d": 75,
    "wall": 6.8,
    "roll": 50
  },
  {
    "number": "92100.176",
    "text": "HakaGerodur GEROthen Druckrohr PE 75x6,8 mm PN16 100 m",
    "d": 75,
    "wall": 6.8,
    "roll": 100
  },
  {
    "number": "92100.190",
    "text": "HakaGerodur GEROthen Druckrohr PE 90x8,2 mm PN16 50 m",
    "d": 90,
    "wall": 8.2,
    "roll": 50
  },
  {
    "number": "92100.191",
    "text": "HakaGerodur GEROthen Druckrohr PE 90x8,2 mm PN16 100 m",
    "d": 90,
    "wall": 8.2,
    "roll": 100
  }
];

export const probeManifolds: (Article & { body: number; outlets: number; d: number; kind: "KH+F" | "IS+F" | "KH" | "IS" | "HY+F" | "HY" })[] = [
  {
    "number": "14762.004",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x40-KH+F",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.005",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x40-KH+F",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.006",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x40-KH+F",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.007",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x40-KH+F",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.008",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x40-KH+F",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.009",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 7x40-KH",
    "body": 125,
    "outlets": 7,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.010",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 8x40-KH",
    "body": 125,
    "outlets": 8,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.011",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 9x40-KH",
    "body": 125,
    "outlets": 9,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.012",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 10x40-KH",
    "body": 125,
    "outlets": 10,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.013",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 11x40-KH",
    "body": 125,
    "outlets": 11,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.014",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 12x40-KH",
    "body": 125,
    "outlets": 12,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.015",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 2x40-KH+F",
    "body": 125,
    "outlets": 2,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.016",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 3x40-KH+F",
    "body": 125,
    "outlets": 3,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.017",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 4x40-KH+F",
    "body": 125,
    "outlets": 4,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.018",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 5x40-KH+F",
    "body": 125,
    "outlets": 5,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.019",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 6x40-KH+F",
    "body": 125,
    "outlets": 6,
    "d": 40,
    "kind": "KH+F"
  },
  {
    "number": "14762.020",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x40-HY+F",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "HY+F"
  },
  {
    "number": "14762.021",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x40-HY+F",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "HY+F"
  },
  {
    "number": "14762.022",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x40-HY+F",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "HY+F"
  },
  {
    "number": "14762.023",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x40-HY+F",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "HY+F"
  },
  {
    "number": "14762.024",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x40-HY+F",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "HY+F"
  },
  {
    "number": "14762.025",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 7x40-HY",
    "body": 125,
    "outlets": 7,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.026",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 8x40-HY",
    "body": 125,
    "outlets": 8,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.027",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 9x40-HY",
    "body": 125,
    "outlets": 9,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.028",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 10x40-HY",
    "body": 125,
    "outlets": 10,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.029",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 11x40-HY",
    "body": 125,
    "outlets": 11,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.030",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 12x40-HY",
    "body": 125,
    "outlets": 12,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.031",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 13x40-HY",
    "body": 125,
    "outlets": 13,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.032",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 2x50-KH",
    "body": 125,
    "outlets": 2,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.033",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 3x50-KH",
    "body": 125,
    "outlets": 3,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.034",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 4x50-KH",
    "body": 125,
    "outlets": 4,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.035",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 5x50-KH",
    "body": 125,
    "outlets": 5,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.036",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 6x50-KH",
    "body": 125,
    "outlets": 6,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.037",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 7x50-KH",
    "body": 125,
    "outlets": 7,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.038",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 8x50-KH",
    "body": 125,
    "outlets": 8,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.039",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 9x50-KH",
    "body": 125,
    "outlets": 9,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.041",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 2x50-HY",
    "body": 125,
    "outlets": 2,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.042",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 3x50-HY",
    "body": 125,
    "outlets": 3,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.043",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 4x50-HY",
    "body": 125,
    "outlets": 4,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.044",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 5x50-HY",
    "body": 125,
    "outlets": 5,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.045",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 6x50-HY",
    "body": 125,
    "outlets": 6,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.046",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 7x50-HY",
    "body": 125,
    "outlets": 7,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.047",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 8x50-HY",
    "body": 125,
    "outlets": 8,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.048",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 9x50-HY",
    "body": 125,
    "outlets": 9,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.049",
    "text": "HakaGerodur SAVE 125 Erdsondenverteiler 10x50-HY",
    "body": 125,
    "outlets": 10,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.062",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x40-KH",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.063",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x40-KH",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.064",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x40-KH",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.065",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x40-KH",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.066",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x40-KH",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "KH"
  },
  {
    "number": "14762.067",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x40-IS",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.068",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x40-IS",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.069",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x40-IS",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.070",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x40-IS",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.071",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x40-IS",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.072",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x50-KH+F",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "KH+F"
  },
  {
    "number": "14762.073",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x50-KH+F",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "KH+F"
  },
  {
    "number": "14762.074",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x50-KH+F",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "KH+F"
  },
  {
    "number": "14762.075",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x50-KH+F",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "KH+F"
  },
  {
    "number": "14762.076",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x50KH+F",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "KH+F"
  },
  {
    "number": "14762.077",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x50-KH",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.078",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x50-KH",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.079",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x50-KH",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.080",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x50-KH",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.081",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x50-KH",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "KH"
  },
  {
    "number": "14762.082",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x50-HY+F",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "HY+F"
  },
  {
    "number": "14762.083",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x50-HY+F",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "HY+F"
  },
  {
    "number": "14762.084",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x50-HY+F",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "HY+F"
  },
  {
    "number": "14762.085",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x50-HY+F",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "HY+F"
  },
  {
    "number": "14762.086",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x50-HY+F",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "HY+F"
  },
  {
    "number": "14762.087",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x40-HY",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.088",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x40-HY",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.089",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x40-HY",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.090",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x40-HY",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.091",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x40-HY",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "HY"
  },
  {
    "number": "14762.092",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 2x50-HY",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.093",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 3x50-HY",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.094",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 4x50-HY",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.095",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 5x50-HY",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.096",
    "text": "HakaGerodur SAVE 97 Erdsondenverteiler 6x50-HY",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "HY"
  },
  {
    "number": "14762.100",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 2x40-IS+F",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.101",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 3x40-IS+F",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.102",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 4x40-IS+F",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.103",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 5x40-IS+F",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.104",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 6x40-IS+F",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.105",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 2x50-IS+F",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.106",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 3x50-IS+F",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.107",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 4x50-IS+F",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.108",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 5x50-IS+F",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.109",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 6x50-IS+F",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.110",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 2x40-IS",
    "body": 97,
    "outlets": 2,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.111",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 3x40-IS",
    "body": 97,
    "outlets": 3,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.112",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 4x40-IS",
    "body": 97,
    "outlets": 4,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.113",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 5x40-IS",
    "body": 97,
    "outlets": 5,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.114",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 6x40-IS",
    "body": 97,
    "outlets": 6,
    "d": 40,
    "kind": "IS"
  },
  {
    "number": "14762.115",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 2x50-IS",
    "body": 97,
    "outlets": 2,
    "d": 50,
    "kind": "IS"
  },
  {
    "number": "14762.116",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 3x50-IS",
    "body": 97,
    "outlets": 3,
    "d": 50,
    "kind": "IS"
  },
  {
    "number": "14762.117",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 4x50-IS",
    "body": 97,
    "outlets": 4,
    "d": 50,
    "kind": "IS"
  },
  {
    "number": "14762.118",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 5x50-IS",
    "body": 97,
    "outlets": 5,
    "d": 50,
    "kind": "IS"
  },
  {
    "number": "14762.119",
    "text": "HakaGerodur SAVE 97 Erdsonden-Verteiler 6x50-IS",
    "body": 97,
    "outlets": 6,
    "d": 50,
    "kind": "IS"
  },
  {
    "number": "14762.121",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 3x40-IS+F",
    "body": 125,
    "outlets": 3,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.122",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 4x40-IS+F",
    "body": 125,
    "outlets": 4,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.123",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 5x40-IS+F",
    "body": 125,
    "outlets": 5,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.124",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 6x40-IS+F",
    "body": 125,
    "outlets": 6,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.125",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 7x40-IS+F",
    "body": 125,
    "outlets": 7,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.126",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 8x40-IS+F",
    "body": 125,
    "outlets": 8,
    "d": 40,
    "kind": "IS+F"
  },
  {
    "number": "14762.127",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 2x50-IS+F",
    "body": 125,
    "outlets": 2,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.128",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 3x50-IS+F",
    "body": 125,
    "outlets": 3,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.129",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 4x50-IS+F",
    "body": 125,
    "outlets": 4,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.130",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 5x50-IS+F",
    "body": 125,
    "outlets": 5,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.131",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 6x50-IS+F",
    "body": 125,
    "outlets": 6,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.132",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 7x50-IS+F",
    "body": 125,
    "outlets": 7,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14762.133",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 8x50-IS+F",
    "body": 125,
    "outlets": 8,
    "d": 50,
    "kind": "IS+F"
  },
  {
    "number": "14672.120",
    "text": "HakaGerodur SAVE 125 Erdsonden-Verteiler 2x40-IS+F",
    "body": 125,
    "outlets": 2,
    "d": 40,
    "kind": "IS+F"
  }
];
