// Generated by scripts/gen-nussbaum-data.mjs from the IGH catalogues (R. Nussbaum AG, Biral AG) – do not edit.

export type CatalogArticle = { number: string; size: string | null; text: string };

/** Nussbaum articles by family (article number before the dot). */
export const nussbaumFamilies = {
  "11002": "Druckreduzierventil mit OP-A-Verschraubung",
  "12102": "Redfil rückspülbar, mit Optipress-A-Anschlussverschraubung",
  "15101": "Rückflussverhinderer EA (Gewinde, für Optiflex-Flowpress mit Übergängen)",
  "18102": "Feinfilter rückspülbar, mit Optipress-A-Anschlussverschraubung",
  "19051": "Wasserenthärter Aquapro-Vita Compact",
  "19053": "Wasserenthärter Aquapro-Vita",
  "24026": "Regulierventil, mit Innengewinde",
  "36030": "Zirkulationsventil, mit Durchflussregulierung selbstständig",
  "67100": "Rohbauset, für Messkapsel Koax",
  "81018": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen",
  "81082": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m",
  "81163": "Optipress-A-Rückflussverhinderer EA",
  "81168": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer",
  "82200": "Optipress-Aquaplus-Schrägsitzventil",
  "82202": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil",
  "82232": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung",
  "86510": "Optiflex-Flowpress-Schrägsitzventil",
  "87153": "Optiflex-Flowpress-Rohr formstabil"
} as const;

export type NussbaumFamily = keyof typeof nussbaumFamilies;

export const nussbaumArticles: Record<NussbaumFamily, CatalogArticle[]> = {
  "11002": [
    {
      "number": "11002.22",
      "size": "15",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 15"
    },
    {
      "number": "11002.23",
      "size": "18",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 18"
    },
    {
      "number": "11002.24",
      "size": "22",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 22"
    },
    {
      "number": "11002.25",
      "size": "28",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 28"
    },
    {
      "number": "11002.26",
      "size": "35",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 35"
    },
    {
      "number": "11002.27",
      "size": "42",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 42"
    },
    {
      "number": "11002.28",
      "size": "54",
      "text": "DRV m. OP-A-Verschraubung, Einstellbereich 2 bar bis 6 bar, 54"
    }
  ],
  "12102": [
    {
      "number": "12102.25",
      "size": "28",
      "text": "Redfil rückspülbar, mit Optipress-A-Anschlussverschraubung, 28"
    },
    {
      "number": "12102.26",
      "size": "35",
      "text": "Redfil rückspülbar, mit Optipress-A-Anschlussverschraubung, 35"
    },
    {
      "number": "12102.27",
      "size": "42",
      "text": "Redfil rückspülbar, mit Optipress-A-Anschlussverschraubung, 42"
    },
    {
      "number": "12102.28",
      "size": "54",
      "text": "Redfil rückspülbar, mit Optipress-A-Anschlussverschraubung, 54"
    }
  ],
  "15101": [
    {
      "number": "15101.04",
      "size": "½",
      "text": "Rückflussverhinderer EA, ½"
    },
    {
      "number": "15101.05",
      "size": "¾",
      "text": "Rückflussverhinderer EA, ¾"
    },
    {
      "number": "15101.06",
      "size": "1",
      "text": "Rückflussverhinderer EA, 1"
    },
    {
      "number": "15101.07",
      "size": "1¼",
      "text": "Rückflussverhinderer EA, 1¼"
    },
    {
      "number": "15101.08",
      "size": "1½",
      "text": "Rückflussverhinderer EA, 1½"
    },
    {
      "number": "15101.09",
      "size": "2",
      "text": "Rückflussverhinderer EA, 2"
    },
    {
      "number": "15101.10",
      "size": "2½",
      "text": "Rückflussverhinderer EA, 2½"
    }
  ],
  "18102": [
    {
      "number": "18102.25",
      "size": "28",
      "text": "Feinfilter rückspülbar, mit Optipress-A-Anschlussverschraubung, 28"
    },
    {
      "number": "18102.26",
      "size": "35",
      "text": "Feinfilter rückspülbar, mit Optipress-A-Anschlussverschraubung, 35"
    },
    {
      "number": "18102.27",
      "size": "42",
      "text": "Feinfilter rückspülbar, mit Optipress-A-Anschlussverschraubung, 42"
    },
    {
      "number": "18102.28",
      "size": "54",
      "text": "Feinfilter rückspülbar, mit Optipress-A-Anschlussverschraubung, 54"
    }
  ],
  "19051": [
    {
      "number": "19051.21",
      "size": "10",
      "text": "Wasserenthärter Aquapro-Vita Compact, 10"
    },
    {
      "number": "19051.22",
      "size": "15",
      "text": "Wasserenthärter Aquapro-Vita Compact, 15"
    },
    {
      "number": "19051.23",
      "size": "25",
      "text": "Wasserenthärter Aquapro-Vita Compact, 25"
    }
  ],
  "19053": [
    {
      "number": "19053.21",
      "size": "50",
      "text": "Wasserenthärter Aquapro-Vita, 50"
    },
    {
      "number": "19053.22",
      "size": "50 HF",
      "text": "Wasserenthärter Aquapro-Vita, 50 HF"
    },
    {
      "number": "19053.23",
      "size": "60",
      "text": "Wasserenthärter Aquapro-Vita, 60"
    },
    {
      "number": "19053.24",
      "size": "75",
      "text": "Wasserenthärter Aquapro-Vita, 75"
    },
    {
      "number": "19053.25",
      "size": "100",
      "text": "Wasserenthärter Aquapro-Vita, 100"
    },
    {
      "number": "19053.26",
      "size": "125",
      "text": "Wasserenthärter Aquapro-Vita, 125"
    }
  ],
  "24026": [
    {
      "number": "24026.05",
      "size": "20 (¾)",
      "text": "Regulierventil, mit Innengewinde, 20 (¾)"
    }
  ],
  "36030": [
    {
      "number": "36030.04",
      "size": "15 (½)",
      "text": "Zirkulationsventil, mit Durchflussregulierung selbstständig, 15 (½)"
    },
    {
      "number": "36030.05",
      "size": "20 (¾)",
      "text": "Zirkulationsventil, mit Durchflussregulierung selbstständig, 20 (¾)"
    }
  ],
  "67100": [
    {
      "number": "67100.05",
      "size": "¾",
      "text": "Rohbauset, für Messkapsel Koax, ¾"
    }
  ],
  "81018": [
    {
      "number": "81018.24",
      "size": "22",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 22"
    },
    {
      "number": "81018.25",
      "size": "28",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 28"
    },
    {
      "number": "81018.26",
      "size": "35",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 35"
    },
    {
      "number": "81018.27",
      "size": "42",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 42"
    },
    {
      "number": "81018.28",
      "size": "54",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 54"
    },
    {
      "number": "81018.70",
      "size": "64",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 64"
    },
    {
      "number": "81018.71",
      "size": "76.1",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 76.1"
    },
    {
      "number": "81018.72",
      "size": "88.9",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 88.9"
    },
    {
      "number": "81018.73",
      "size": "108",
      "text": "Optipress-Aquaplus-Temperaturmessstelle, für gedämmte Leitungen, 108"
    }
  ],
  "81082": [
    {
      "number": "81082.22",
      "size": "15",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 15"
    },
    {
      "number": "81082.23",
      "size": "18",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 18"
    },
    {
      "number": "81082.24",
      "size": "22",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 22"
    },
    {
      "number": "81082.25",
      "size": "28",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 28"
    },
    {
      "number": "81082.26",
      "size": "35",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 35"
    },
    {
      "number": "81082.27",
      "size": "42",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 42"
    },
    {
      "number": "81082.28",
      "size": "54",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 54"
    },
    {
      "number": "81082.29",
      "size": "76.1",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 76.1"
    },
    {
      "number": "81082.30",
      "size": "88.9",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 88.9"
    },
    {
      "number": "81082.31",
      "size": "108",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 108"
    },
    {
      "number": "81082.32",
      "size": "64",
      "text": "Optipress-Edelstahlrohr 1.4521, Stange à 6 m, 64"
    }
  ],
  "81163": [
    {
      "number": "81163.22",
      "size": "15",
      "text": "Optipress-A-Rückflussverhinderer EA, 15"
    },
    {
      "number": "81163.23",
      "size": "18",
      "text": "Optipress-A-Rückflussverhinderer EA, 18"
    },
    {
      "number": "81163.24",
      "size": "22",
      "text": "Optipress-A-Rückflussverhinderer EA, 22"
    },
    {
      "number": "81163.25",
      "size": "28",
      "text": "Optipress-A-Rückflussverhinderer EA, 28"
    },
    {
      "number": "81163.26",
      "size": "35",
      "text": "Optipress-A-Rückflussverhinderer EA, 35"
    },
    {
      "number": "81163.27",
      "size": "42",
      "text": "Optipress-A-Rückflussverhinderer EA, 42"
    },
    {
      "number": "81163.28",
      "size": "54",
      "text": "Optipress-A-Rückflussverhinderer EA, 54"
    }
  ],
  "81168": [
    {
      "number": "81168.24",
      "size": "22 x ¾",
      "text": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer, 22 x ¾"
    },
    {
      "number": "81168.25",
      "size": "28 x ¾",
      "text": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer, 28 x ¾"
    },
    {
      "number": "81168.26",
      "size": "35 x ¾",
      "text": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer, 35 x ¾"
    },
    {
      "number": "81168.27",
      "size": "42 x 1",
      "text": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer, 42 x 1"
    },
    {
      "number": "81168.30",
      "size": "35 x 1",
      "text": "OP-A-Absperr-Sicherheitsgarnitur SW, zu Stand-Wassererwärmer, 35 x 1"
    }
  ],
  "82200": [
    {
      "number": "82200.22",
      "size": "15",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 15"
    },
    {
      "number": "82200.23",
      "size": "18",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 18"
    },
    {
      "number": "82200.24",
      "size": "22",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 22"
    },
    {
      "number": "82200.25",
      "size": "28",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 28"
    },
    {
      "number": "82200.26",
      "size": "35",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 35"
    },
    {
      "number": "82200.27",
      "size": "42",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 42"
    },
    {
      "number": "82200.28",
      "size": "54",
      "text": "Optipress-Aquaplus-Schrägsitzventil, 54"
    }
  ],
  "82202": [
    {
      "number": "82202.22",
      "size": "15",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 15"
    },
    {
      "number": "82202.23",
      "size": "18",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 18"
    },
    {
      "number": "82202.24",
      "size": "22",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 22"
    },
    {
      "number": "82202.25",
      "size": "28",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 28"
    },
    {
      "number": "82202.26",
      "size": "35",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 35"
    },
    {
      "number": "82202.27",
      "size": "42",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 42"
    },
    {
      "number": "82202.28",
      "size": "54",
      "text": "Optipress-Aquaplus-Schrägsitzventil, mit Entleerventil, 54"
    }
  ],
  "82232": [
    {
      "number": "82232.21",
      "size": "28 x 22",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 28 x 22"
    },
    {
      "number": "82232.22",
      "size": "28 x 28",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 28 x 28"
    },
    {
      "number": "82232.23",
      "size": "35 x 22",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 35 x 22"
    },
    {
      "number": "82232.24",
      "size": "35 x 28",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 35 x 28"
    },
    {
      "number": "82232.25",
      "size": "35 x 35",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 35 x 35"
    },
    {
      "number": "82232.26",
      "size": "42 x 22",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 42 x 22"
    },
    {
      "number": "82232.27",
      "size": "42 x 28",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 42 x 28"
    },
    {
      "number": "82232.28",
      "size": "42 x 35",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 42 x 35"
    },
    {
      "number": "82232.29",
      "size": "42 x 42",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 42 x 42"
    },
    {
      "number": "82232.30",
      "size": "54 x 22",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 54 x 22"
    },
    {
      "number": "82232.31",
      "size": "54 x 28",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 54 x 28"
    },
    {
      "number": "82232.32",
      "size": "54 x 35",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 54 x 35"
    },
    {
      "number": "82232.33",
      "size": "54 x 42",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 54 x 42"
    },
    {
      "number": "82232.34",
      "size": "54 x 54",
      "text": "Optipress-Aquaplus-Batterieventil, mit Optipress-A-Anschlussverschraubung, 54 x 54"
    }
  ],
  "86510": [
    {
      "number": "86510.22",
      "size": "16",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 16"
    },
    {
      "number": "86510.23",
      "size": "20",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 20"
    },
    {
      "number": "86510.24",
      "size": "25",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 25"
    },
    {
      "number": "86510.25",
      "size": "32",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 32"
    },
    {
      "number": "86510.26",
      "size": "40",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 40"
    },
    {
      "number": "86510.27",
      "size": "50",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 50"
    },
    {
      "number": "86510.28",
      "size": "63",
      "text": "Optiflex-Flowpress-Schrägsitzventil, 63"
    }
  ],
  "87153": [
    {
      "number": "87153.21",
      "size": "16",
      "text": "Optiflex-Flowpress-Rohr formstabil, 16"
    },
    {
      "number": "87153.22",
      "size": "20",
      "text": "Optiflex-Flowpress-Rohr formstabil, 20"
    },
    {
      "number": "87153.23",
      "size": "25",
      "text": "Optiflex-Flowpress-Rohr formstabil, 25"
    },
    {
      "number": "87153.24",
      "size": "32",
      "text": "Optiflex-Flowpress-Rohr formstabil, 32"
    }
  ]
};

/** Biral hot-water circulation pumps: series, connection DN, max. head [m] (from the type name), length [mm]; «valves»: with check valve and ball valve (RV KH). */
export type BiralPump = { number: string; name: string; series: string; dn: number; head: number; length: number; valves: boolean };

export const biralPumps: BiralPump[] = [
  {
    "number": "7000001518",
    "name": "CompAX 15-1 175 BLUE RV KH",
    "series": "CompAX",
    "dn": 15,
    "head": 1,
    "length": 175,
    "valves": true
  },
  {
    "number": "7000001511",
    "name": "CompAX 20-1 120 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 1,
    "length": 120,
    "valves": false
  },
  {
    "number": "7000001512",
    "name": "CompAX 20-1 150 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 1,
    "length": 150,
    "valves": false
  },
  {
    "number": "7000001519",
    "name": "CompAX 15-1.6 175 BLUE RV KH",
    "series": "CompAX",
    "dn": 15,
    "head": 1.6,
    "length": 175,
    "valves": true
  },
  {
    "number": "7000001520",
    "name": "CompAX 15-2.5 175 BLUE RV KH",
    "series": "CompAX",
    "dn": 15,
    "head": 2.5,
    "length": 175,
    "valves": true
  },
  {
    "number": "7000001530",
    "name": "CompAX 20-2.5 120 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 2.5,
    "length": 120,
    "valves": false
  },
  {
    "number": "7000001513",
    "name": "CompAX 20-4 120 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 4,
    "length": 120,
    "valves": false
  },
  {
    "number": "7000001514",
    "name": "CompAX 20-4 150 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 4,
    "length": 150,
    "valves": false
  },
  {
    "number": "7000000163",
    "name": "ModulA 25-4 180 BLUE",
    "series": "ModulA",
    "dn": 25,
    "head": 4,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000001515",
    "name": "CompAX 25-4 180 BLUE",
    "series": "CompAX",
    "dn": 25,
    "head": 4,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000168",
    "name": "ModulA 32-4 180 BLUE",
    "series": "ModulA",
    "dn": 32,
    "head": 4,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000001516",
    "name": "CompAX 20-6 150 BLUE",
    "series": "CompAX",
    "dn": 20,
    "head": 6,
    "length": 150,
    "valves": false
  },
  {
    "number": "7000000164",
    "name": "ModulA 25-6 180 BLUE",
    "series": "ModulA",
    "dn": 25,
    "head": 6,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000001517",
    "name": "CompAX 25-6 180 BLUE",
    "series": "CompAX",
    "dn": 25,
    "head": 6,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000169",
    "name": "ModulA 32-6 180 BLUE",
    "series": "ModulA",
    "dn": 32,
    "head": 6,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000165",
    "name": "ModulA 25-8 180 BLUE",
    "series": "ModulA",
    "dn": 25,
    "head": 8,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000170",
    "name": "ModulA 32-8 180 BLUE",
    "series": "ModulA",
    "dn": 32,
    "head": 8,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000166",
    "name": "ModulA 25-10 180 BLUE",
    "series": "ModulA",
    "dn": 25,
    "head": 10,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000171",
    "name": "ModulA 32-10 180 BLUE",
    "series": "ModulA",
    "dn": 32,
    "head": 10,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000173",
    "name": "ModulA 40-11 250 BLUE",
    "series": "ModulA",
    "dn": 40,
    "head": 11,
    "length": 250,
    "valves": false
  },
  {
    "number": "7000000167",
    "name": "ModulA 25-12 180 BLUE",
    "series": "ModulA",
    "dn": 25,
    "head": 12,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000172",
    "name": "ModulA 32-12 180 BLUE",
    "series": "ModulA",
    "dn": 32,
    "head": 12,
    "length": 180,
    "valves": false
  },
  {
    "number": "7000000174",
    "name": "ModulA 40-12 250 BLUE",
    "series": "ModulA",
    "dn": 40,
    "head": 12,
    "length": 250,
    "valves": false
  },
  {
    "number": "7000000175",
    "name": "ModulA 40-18 250 BLUE",
    "series": "ModulA",
    "dn": 40,
    "head": 18,
    "length": 250,
    "valves": false
  }
];
