// Generated by scripts/gen-sanitary-insulation.mjs from the IGH catalogue of Meier Tobler – do not edit.

/** Pipe insulation shell: material, Meier Tobler article, inner diameter (pipe OD) and thickness [mm]. */
export type InsulationShell = { material: "mineralwool" | "pir"; number: string; text: string; od: number; mm: number; unit: string };

export const insulationShells: InsulationShell[] = [
  {
    "material": "mineralwool",
    "number": "01387.152",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 15/20mm",
    "od": 15,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.182",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 18/20mm",
    "od": 18,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.222",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 22/20mm",
    "od": 22,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.282",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 28/20mm",
    "od": 28,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.352",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 35/20mm",
    "od": 35,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.422",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 42/20mm",
    "od": 42,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.482",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/20mm",
    "od": 48,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.542",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/20mm",
    "od": 54,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.602",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/20mm",
    "od": 60,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.642",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/20mm",
    "od": 64,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.762",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/20mm",
    "od": 76,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.892",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/20mm",
    "od": 89,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.153",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 15/30mm",
    "od": 15,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.183",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 18/30mm",
    "od": 18,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.223",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 22/30mm",
    "od": 22,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.283",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 28/30mm",
    "od": 28,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.353",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 35/30mm",
    "od": 35,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.423",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 42/30mm",
    "od": 42,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.483",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/30mm",
    "od": 48,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.543",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/30mm",
    "od": 54,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.603",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/30mm",
    "od": 60,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.643",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/30mm",
    "od": 64,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.763",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/30mm",
    "od": 76,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.893",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/30mm",
    "od": 89,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.101",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 101/30mm",
    "od": 101,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.108",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/30mm",
    "od": 108,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.114",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/30mm",
    "od": 114,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.126",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 126/30mm",
    "od": 126,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.133",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/30mm",
    "od": 133,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.140",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 140/30mm",
    "od": 140,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.161",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 161/30mm",
    "od": 161,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.201",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 201/30mm",
    "od": 201,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.219",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/30mm",
    "od": 219,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.154",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 15/40mm",
    "od": 15,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.184",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 18/40mm",
    "od": 18,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.224",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 22/40mm",
    "od": 22,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.284",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 28/40mm",
    "od": 28,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.354",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 35/40mm",
    "od": 35,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.424",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 42/40mm",
    "od": 42,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.484",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/40mm",
    "od": 48,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.544",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/40mm",
    "od": 54,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.604",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/40mm",
    "od": 60,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.644",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/40mm",
    "od": 64,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.764",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/40mm",
    "od": 76,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.894",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/40mm",
    "od": 89,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.109",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/40mm",
    "od": 108,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.115",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/40mm",
    "od": 114,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.134",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/40mm",
    "od": 133,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.160",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 159/40mm",
    "od": 159,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.169",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 168/40mm",
    "od": 168,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.220",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/40mm",
    "od": 219,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.185",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 18/50mm",
    "od": 18,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.225",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 22/50mm",
    "od": 22,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.285",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 28/50mm",
    "od": 28,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.355",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 35/50mm",
    "od": 35,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.425",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 42/50mm",
    "od": 42,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.485",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/50mm",
    "od": 48,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.545",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/50mm",
    "od": 54,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.605",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/50mm",
    "od": 60,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.645",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/50mm",
    "od": 64,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.765",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/50mm",
    "od": 76,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.895",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/50mm",
    "od": 89,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.102",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 101/50mm",
    "od": 101,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.110",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/50mm",
    "od": 108,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.116",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/50mm",
    "od": 114,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.135",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/50mm",
    "od": 133,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.141",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 140/50mm",
    "od": 140,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.159",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 159/50mm",
    "od": 159,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.170",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 168/50mm",
    "od": 168,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.221",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/50mm",
    "od": 219,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.186",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 18/60mm",
    "od": 18,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.226",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 22/60mm",
    "od": 22,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.286",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 28/60mm",
    "od": 28,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.356",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 35/60mm",
    "od": 35,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.426",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 42/60mm",
    "od": 42,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.486",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/60mm",
    "od": 48,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.546",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/60mm",
    "od": 54,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.606",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/60mm",
    "od": 60,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.646",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/60mm",
    "od": 64,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.766",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/60mm",
    "od": 76,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.896",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/60mm",
    "od": 89,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.111",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/60mm",
    "od": 108,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.117",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/60mm",
    "od": 114,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.136",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/60mm",
    "od": 133,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.142",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 140/60mm",
    "od": 140,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.163",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 159/60mm",
    "od": 159,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.227",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/60mm",
    "od": 219,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.488",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 48/80mm",
    "od": 48,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.548",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 54/80mm",
    "od": 54,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.608",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 60/80mm",
    "od": 60,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.648",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 64/80mm",
    "od": 64,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.768",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 76/80mm",
    "od": 76,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.898",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/80mm",
    "od": 89,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.112",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/80mm",
    "od": 108,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.118",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/80mm",
    "od": 114,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.137",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/80mm",
    "od": 133,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.143",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 140/80mm",
    "od": 140,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.164",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 159/80mm",
    "od": 159,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.171",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 168/80mm",
    "od": 168,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.228",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/80mm",
    "od": 219,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.891",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 89/100mm",
    "od": 89,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.113",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 108/100mm",
    "od": 108,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.119",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 114/100mm",
    "od": 114,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.138",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 133/100mm",
    "od": 133,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.144",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 140/100mm",
    "od": 140,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.165",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 159/100mm",
    "od": 159,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.172",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 168/100mm",
    "od": 168,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "mineralwool",
    "number": "01387.229",
    "text": "ROHHE r.Heat ® A Steinwolle Rohrschale Alu Kaschiert 219/100mm",
    "od": 219,
    "mm": 100,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.100",
    "text": "swisspor Kisodur PIR Alu Schalen 15x20 mm",
    "od": 15,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.101",
    "text": "swisspor Kisodur PIR Alu Schalen 18x20 mm",
    "od": 18,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.102",
    "text": "swisspor Kisodur PIR Alu Schalen 22x20 mm",
    "od": 22,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.103",
    "text": "swisspor Kisodur PIR Alu Schalen 28x20 mm",
    "od": 28,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.104",
    "text": "swisspor Kisodur PIR Alu Schalen 35x20 mm",
    "od": 35,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.105",
    "text": "swisspor Kisodur PIR Alu Schalen 42x20 mm",
    "od": 42,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.106",
    "text": "swisspor Kisodur PIR Alu Schalen 48x20 mm",
    "od": 48,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.107",
    "text": "swisspor Kisodur PIR Alu Schalen 54x20 mm",
    "od": 54,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.108",
    "text": "swisspor Kisodur PIR Alu Schalen 60x20 mm",
    "od": 60,
    "mm": 20,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.110",
    "text": "swisspor Kisodur PIR Alu Schalen 15x30 mm",
    "od": 15,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.111",
    "text": "swisspor Kisodur PIR Alu Schalen 18x30 mm",
    "od": 18,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.112",
    "text": "swisspor Kisodur PIR Alu Schalen 22x30 mm",
    "od": 22,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.121",
    "text": "swisspor Kisodur PIR Alu Schalen 28x30 mm",
    "od": 28,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.113",
    "text": "swisspor Kisodur PIR Alu Schalen 35x30 mm",
    "od": 35,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.114",
    "text": "swisspor Kisodur PIR Alu Schalen 42x30 mm",
    "od": 42,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.115",
    "text": "swisspor Kisodur PIR Alu Schalen 48x30 mm",
    "od": 48,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.116",
    "text": "swisspor Kisodur PIR Alu Schalen 54x30 mm",
    "od": 54,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.117",
    "text": "swisspor Kisodur PIR Alu Schalen 60x30 mm",
    "od": 60,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.118",
    "text": "swisspor Kisodur PIR Alu Schalen 64x30 mm",
    "od": 64,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.119",
    "text": "swisspor Kisodur PIR Alu Schalen 67x30 mm",
    "od": 67,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.120",
    "text": "swisspor Kisodur PIR Alu Schalen 76x30 mm",
    "od": 76,
    "mm": 30,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.130",
    "text": "swisspor Kisodur PIR Alu Schalen 15x40 mm",
    "od": 15,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.131",
    "text": "swisspor Kisodur PIR Alu Schalen 18x40 mm",
    "od": 18,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.132",
    "text": "swisspor Kisodur PIR Alu Schalen 22x40 mm",
    "od": 22,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.133",
    "text": "swisspor Kisodur PIR Alu Schalen 28x40 mm",
    "od": 28,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.134",
    "text": "swisspor Kisodur PIR Alu Schalen 35x40 mm",
    "od": 35,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.135",
    "text": "swisspor Kisodur PIR Alu Schalen 42x40 mm",
    "od": 42,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.136",
    "text": "swisspor Kisodur PIR Alu Schalen 48x40 mm",
    "od": 48,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.137",
    "text": "swisspor Kisodur PIR Alu Schalen 54x40 mm",
    "od": 54,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.138",
    "text": "swisspor Kisodur PIR Alu Schalen 60x40 mm",
    "od": 60,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.139",
    "text": "swisspor Kisodur PIR Alu Schalen 64x40 mm",
    "od": 64,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.140",
    "text": "swisspor Kisodur PIR Alu Schalen 67x40 mm",
    "od": 67,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.141",
    "text": "swisspor Kisodur PIR Alu Schalen 76x40 mm",
    "od": 76,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.142",
    "text": "swisspor Kisodur PIR Alu Schalen 89x40 mm",
    "od": 89,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.143",
    "text": "swisspor Kisodur PIR Alu Schalen 110x40 mm",
    "od": 110,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.144",
    "text": "swisspor Kisodur PIR Alu Schalen 114x40 mm",
    "od": 114,
    "mm": 40,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.150",
    "text": "swisspor Kisodur PIR Alu Schalen 22x50 mm",
    "od": 22,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.151",
    "text": "swisspor Kisodur PIR Alu Schalen 28x50 mm",
    "od": 28,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.152",
    "text": "swisspor Kisodur PIR Alu Schalen 35x50 mm",
    "od": 35,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.153",
    "text": "swisspor Kisodur PIR Alu Schalen 42x50 mm",
    "od": 42,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.154",
    "text": "swisspor Kisodur PIR Alu Schalen 48x50 mm",
    "od": 48,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.155",
    "text": "swisspor Kisodur PIR Alu Schalen 54x50 mm",
    "od": 54,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.156",
    "text": "swisspor Kisodur PIR Alu Schalen 60x50 mm",
    "od": 60,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.157",
    "text": "swisspor Kisodur PIR Alu Schalen 64x50 mm",
    "od": 64,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.158",
    "text": "swisspor Kisodur PIR Alu Schalen 67x50 mm",
    "od": 67,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.159",
    "text": "swisspor Kisodur PIR Alu Schalen 76x50 mm",
    "od": 76,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.160",
    "text": "swisspor Kisodur PIR Alu Schalen 89x50 mm",
    "od": 89,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.161",
    "text": "swisspor Kisodur PIR Alu Schalen 110x50 mm",
    "od": 110,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.162",
    "text": "swisspor Kisodur PIR Alu Schalen 114x50 mm",
    "od": 114,
    "mm": 50,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.170",
    "text": "swisspor Kisodur PIR Alu Schalen 35x60 mm",
    "od": 35,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.171",
    "text": "swisspor Kisodur PIR Alu Schalen 42x60 mm",
    "od": 42,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.172",
    "text": "swisspor Kisodur PIR Alu Schalen 48x60 mm",
    "od": 48,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.173",
    "text": "swisspor Kisodur PIR Alu Schalen 54x60 mm",
    "od": 54,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.174",
    "text": "swisspor Kisodur PIR Alu Schalen 60x60 mm",
    "od": 60,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.175",
    "text": "swisspor Kisodur PIR Alu Schalen 64x60 mm",
    "od": 64,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.176",
    "text": "swisspor Kisodur PIR Alu Schalen 67x60 mm",
    "od": 67,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.177",
    "text": "swisspor Kisodur PIR Alu Schalen 76x60 mm",
    "od": 76,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.178",
    "text": "swisspor Kisodur PIR Alu Schalen 89x60 mm",
    "od": 89,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.179",
    "text": "swisspor Kisodur PIR Alu Schalen 110x60 mm",
    "od": 110,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.180",
    "text": "swisspor Kisodur PIR Alu Schalen 114x60 mm",
    "od": 114,
    "mm": 60,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.190",
    "text": "swisspor Kisodur PIR Alu Schalen 76x80 mm",
    "od": 76,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.191",
    "text": "swisspor Kisodur PIR Alu Schalen 89x80 mm",
    "od": 89,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.192",
    "text": "swisspor Kisodur PIR Alu Schalen 110x80 mm",
    "od": 110,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.193",
    "text": "swisspor Kisodur PIR Alu Schalen 114x80 mm",
    "od": 114,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.194",
    "text": "swisspor Kisodur PIR Alu Schalen 127x80 mm",
    "od": 127,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.195",
    "text": "swisspor Kisodur PIR Alu Schalen 140x80 mm",
    "od": 140,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.196",
    "text": "swisspor Kisodur PIR Alu Schalen 159x80 mm",
    "od": 159,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.197",
    "text": "swisspor Kisodur PIR Alu Schalen 168x80 mm",
    "od": 168,
    "mm": 80,
    "unit": "m"
  },
  {
    "material": "pir",
    "number": "01436.198",
    "text": "swisspor Kisodur PIR Alu Schalen 219x80 mm",
    "od": 219,
    "mm": 80,
    "unit": "m"
  }
];
